# babel parser for various es7+ features
parser = 'babylon'

# formatting options
printWidth         = 70
tabWidth           = 2
useTabs            = false
semi               = true
singleQuote        = false
trailingComma      = 'all'
bracketSpacing     = false
jsxBracketSameLine = false
arrowParens        = 'avoid'
